### ISSUE TITLE
文档说是支持了array类型，但是测试报错

### ISSUE THREAD

**Issue by pigeon-geng** [51nb/marble#12]
@Test
  public void testCreateTableFromRowListWithSqlType() {

    List<Map<String, Object>> rowList = new ArrayList<>();
    Map<String, Object> row1 = new HashMap<>();
    row1.put("c1", "a");
    row1.put("c2", 0.1);
    row1.put("c3", new Date().getTime());
    row1.put("c4", Lists.newArrayList("a", "n"));

    rowList.add(row1);
    Map<String, Object> row2 = new HashMap<>();
    row2.put("c1", "b");
    row2.put("c2", 0.2);
    row2.put("c3", new Date().getTime());
    row1.put("c4", Lists.newArrayList("a", "n"));

    rowList.add(row2);

    Map<String, SqlTypeName> sqlTypeMap = new HashMap<>();
    sqlTypeMap.put("c1", SqlTypeName.VARCHAR);
    sqlTypeMap.put("c2", SqlTypeName.DOUBLE);
    sqlTypeMap.put("c3", SqlTypeName.TIMESTAMP);
    sqlTypeMap.put("c4", SqlTypeName.ARRAY);

    DataTable dataTable = tableEnv.fromRowListWithSqlTypeMap(rowList, sqlTypeMap);
    tableEnv.registerTable("t", dataTable);
    DataTable queryResult = tableEnv.sqlQuery("select * from t");
    System.out.println(queryResult.toMapList());
  }

测试报错

java.lang.AssertionError: use createArrayType() instead

	at org.apache.calcite.sql.type.SqlTypeFactoryImpl.assertBasic(SqlTypeFactoryImpl.java:221)
	at org.apache.calcite.sql.type.SqlTypeFactoryImpl.createSqlType(SqlTypeFactoryImpl.java:48)
	at org.apache.calcite.rel.type.RelDataTypeFactory$Builder.add(RelDataTypeFactory.java:476)
	at org.apache.calcite.rel.type.RelDataTypeFactory$FieldInfoBuilder.add(RelDataTypeFactory.java:377)
	at org.apache.calcite.rel.type.RelDataTypeFactory$FieldInfoBuilder.add(RelDataTypeFactory.java:365)
	at org.apache.calcite.table.TableEnv.lambda$fromRowListWithSqlTypeMap$2(TableEnv.java:557)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.apache.calcite.table.TableEnv.fromRowListWithSqlTypeMap(TableEnv.java:556)
	at org.apache.calcite.table.TableEnvTest.testCreateTableFromRowListWithSqlType(TableEnvTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by liuyankuankuan** [comment]
你好 我也遇到了同样的问题 请问你最后对array类型是怎么处理的呢

**Comment by LaiZhou** [comment]
Array 解析应该是不支持的，查询可以，这个feature之前没用到，没搞，有时间我可以研究下，最近比较忙。

**Comment by liuyankuankuan** [comment]
您好，
&nbsp; &nbsp;很荣幸收到回信，想趁此机会描述一下我遇到的问题，希望得到您的回复。


&nbsp; &nbsp;我现在需要用到的具体使用场景如下：
&nbsp; &nbsp;比如：对于一个Cat类，里面包含三个字段
&nbsp; &nbsp;class Cat{
&nbsp; &nbsp;		 private String name;
&nbsp; &nbsp;		 private String age;
&nbsp; &nbsp;		 private String color;
&nbsp; &nbsp;}
&nbsp; &nbsp;主要诉求是对List<Cat&gt;数据进行建表，即存入DataTable结构里面，List里存入如下两条数据
&nbsp; &nbsp;List<Cat&gt; catList = new ArrayList<&gt;();
&nbsp; &nbsp;Cat cat1 = new Cat("gali","3","yellow");
&nbsp; &nbsp;Cat cat2 = new Cat("fafa","4","white");
&nbsp; &nbsp;catList.add(cat1);
&nbsp; &nbsp;catList.add(cat2);


&nbsp; &nbsp;目标：把整个catList的信息存储到一行的一个格子中，能够使用sql语句查询到cat1和cat2的信息，不需要定位到cat.name这一层，能够完整拿出cat1即可，类似array[Cat]的形式。


&nbsp; &nbsp;使用的语句是
&nbsp; &nbsp;sqlTypeMap.put("catList",SqlTypeName.ARRAY);
&nbsp; &nbsp;row1.put("catList",catList);
&nbsp; &nbsp;rowList.add(row1);
&nbsp; &nbsp;DataTable dataTable = tableEnv.fromRowListWithSqlTypeMap(rowList,sqlTypeMap);


&nbsp; &nbsp;基于以上操作，在执行“DataTable dataTable = tableEnv.fromRowListWithSqlTypeMap(rowList,sqlTypeMap);”这一步时报错，具体为：
&nbsp; &nbsp;“java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: class null has 0 fields ！”


&nbsp; &nbsp;因此，我想向您请教的问题是：
&nbsp; &nbsp;1、现在使用tableEnv.fromRowListWithSqlTypeMap(rowList,sqlTypeMap)方法时，是否支持定义sqlTypeMap的类型定为“SqlTypeName.ARRAY”？
&nbsp; &nbsp;2、为了实现我的拿出cat1的目标（如上所述），除了现在的使用SqlTypeName.ARRAY定义的方式之外，我是否错过了别的呢？比如您提到的支持Array查询，是否能跟我的诉求相结合？


&nbsp; &nbsp;非常期待您的回信！
&nbsp; &nbsp;
&nbsp; &nbsp;祝好！！！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "51nb/marble"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 晚上9:33
收件人:&nbsp;"51nb/marble"<marble@noreply.github.com&gt;;
抄送:&nbsp;"黄倩"<huangqian9587@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [51nb/marble] 文档说是支持了array类型，但是测试报错 (#12)





 
Array 解析应该是不支持的，查询可以，这个feature之前没用到，没搞，有时间我可以研究下，最近比较忙。

**Comment by LaiZhou** [comment]
这个功能需要自己扩展实现的，因为Calcite不知道怎么处理自定义对象的转换。
参考Calcite默认的JavaTypeFactory ，这里在创建Array时候不支持自定义Class
https://github.com/apache/calcite/blob/155276591288615c4d02d55fb7d77eceb2e24b2d/core/src/main/java/org/apache/calcite/jdbc/JavaTypeFactoryImpl.java#L137
所以需要实现自己的JavaTypeFactory，你的需求可以有2种实现，一种是支持List<String>
把Pojo对象序列化为Json String，插入，这个需要修改目前的PojoTypeConverter。
另外一种彻底的做法是，支持嵌套的List<Pojo> , 把Pojo的字段遍历递归，支持所有Java Class到Calcite的转换，
比如Cat到StructType。
目前的PojoTypeConverter没有考虑复杂的类型，有兴趣可以考虑自己实现个PR。
